-- Daily View dashboard: recurring-event series foundation (birthday/anniversary reminders).
-- Adds `dv_event_series` per the build spec's section 6.2 (RFC 5545 rrule design), `series_id`
-- on `dv_event`, a `birthday` event type and `recurring_series` event source, and a
-- yearly-only occurrence generator + trigger. Weekly/daily/monthly rrule values are accepted by
-- the schema for forward-compatibility but are not yet generated -- see
-- dv_generate_series_occurrences() below.
--
-- Verified against the live schema before writing this file: dv_event_type currently seeds
-- appointment/meal/medication/other/reminder/routine/task/visit (no 'birthday');
-- dv_event_source seeds calendar_sync/manual/mobile_message/system_generated/web_dashboard (no
-- 'recurring_series'); dv_event_status seeds cancelled/completed/missed/scheduled;
-- dv_event_visibility seeds display/private/supporters_only. All differ from the informal spec
-- doc's seed lists, per the existing caution in 20260706112913_dv_today_page.sql.
--
-- Scope note: this project also hosts an unrelated schema (block/cube/cuboid/...) for a
-- separate app. Nothing here touches any table outside the dv_ prefix.

-- ============================================================================
-- 1. dv_event_series
-- ============================================================================

create table if not exists public.dv_event_series (
  series_id             bigint generated by default as identity primary key,
  account_id            bigint not null references public.dv_account(account_id),
  title                 text not null,
  description           text null,
  start_date            date not null,
  end_date              date null,
  start_time            time null,
  end_time              time null,
  rrule                 text not null,
  event_type_id         bigint null references public.dv_event_type(event_type_id),
  event_visibility_id   bigint not null references public.dv_event_visibility(event_visibility_id),
  event_source_id       bigint null references public.dv_event_source(event_source_id),
  event_accuracy_id     bigint null references public.dv_event_accuracy(event_accuracy_id),
  display_priority      smallint not null default 5,
  show_on_display       boolean not null default true,
  is_active             boolean not null default true,
  created_by_user_id    bigint null references public.dv_user(user_id),
  updated_by_user_id    bigint null references public.dv_user(user_id),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  deleted_at            timestamptz null
);

create index if not exists dv_event_series_account_idx
  on public.dv_event_series (account_id)
  where deleted_at is null;

alter table public.dv_event_series enable row level security;

-- Mirrors dv_event's own policies exactly (20260705163726_dv_login_access.sql:136-200).
create policy dv_event_series_select_member on public.dv_event_series
  for select to authenticated
  using (
    exists (
      select 1 from public.dv_account_user au
      join public.dv_user u on u.user_id = au.user_id
      where au.account_id = dv_event_series.account_id
        and u.auth_user_id = auth.uid()
        and u.is_active = true
        and au.deleted_at is null
    )
  );

create policy dv_event_series_insert_manage on public.dv_event_series
  for insert to authenticated
  with check (
    exists (
      select 1 from public.dv_account_user au
      join public.dv_user u on u.user_id = au.user_id
      where au.account_id = dv_event_series.account_id
        and u.auth_user_id = auth.uid()
        and u.is_active = true
        and au.deleted_at is null
        and au.can_manage_events = true
    )
  );

create policy dv_event_series_update_manage on public.dv_event_series
  for update to authenticated
  using (
    exists (
      select 1 from public.dv_account_user au
      join public.dv_user u on u.user_id = au.user_id
      where au.account_id = dv_event_series.account_id
        and u.auth_user_id = auth.uid()
        and u.is_active = true
        and au.deleted_at is null
        and au.can_manage_events = true
    )
  )
  with check (
    exists (
      select 1 from public.dv_account_user au
      join public.dv_user u on u.user_id = au.user_id
      where au.account_id = dv_event_series.account_id
        and u.auth_user_id = auth.uid()
        and u.is_active = true
        and au.deleted_at is null
        and au.can_manage_events = true
    )
  );

create policy dv_event_series_delete_manage on public.dv_event_series
  for delete to authenticated
  using (
    exists (
      select 1 from public.dv_account_user au
      join public.dv_user u on u.user_id = au.user_id
      where au.account_id = dv_event_series.account_id
        and u.auth_user_id = auth.uid()
        and u.is_active = true
        and au.deleted_at is null
        and au.can_manage_events = true
    )
  );

create trigger dv_event_series_set_updated_at
  before update on public.dv_event_series
  for each row execute function public.dv_set_updated_at();

-- ============================================================================
-- 2. dv_event.series_id
-- ============================================================================

alter table public.dv_event
  add column if not exists series_id bigint null references public.dv_event_series(series_id);

-- Marks an occurrence as edited independently of its series ("this occurrence only" in the
-- dashboard's edit dialog). dv_sync_series_occurrences() below skips overridden rows when a
-- series-level edit ("entire series") pushes new field values out to future occurrences -- this
-- is what implements the spec's "editing the series updates future, non-overridden occurrences
-- only" rule. The dashboard is responsible for setting this to true on an occurrence-only edit;
-- it is never set by the series-sync path itself.
alter table public.dv_event
  add column if not exists series_overridden boolean not null default false;

create index if not exists dv_event_series_id_idx
  on public.dv_event (series_id)
  where series_id is not null and deleted_at is null;

-- ============================================================================
-- 3. Seed additions
-- ============================================================================

insert into public.dv_event_type (event_type)
select 'birthday'
where not exists (select 1 from public.dv_event_type where event_type = 'birthday');

insert into public.dv_event_source (event_source)
select 'recurring_series'
where not exists (select 1 from public.dv_event_source where event_source = 'recurring_series');

-- ============================================================================
-- 4. dv_generate_series_occurrences(): yearly-only occurrence generator
-- ============================================================================
-- Materializes concrete dv_event rows for a yearly-recurring series, per the build spec's
-- "dv_event_series is the source definition; dv_event stores concrete occurrence records"
-- rule. Only FREQ=YEARLY rrules are understood right now -- anything else is a documented
-- no-op, so the schema is ready for weekly/monthly recurrence later without blocking this
-- release. Re-running for the same series is idempotent (skips dates that already have a
-- dv_event row for that series, regardless of that row's status -- this is what makes
-- "cancelling one occurrence must not be regenerated" hold).
--
-- dv_event's own BEFORE INSERT trigger (dv_event_enforce_visibility, from
-- 20260706112913_dv_today_page.sql) already forces show_on_display=false for
-- private/supporters_only visibility on every row this function inserts, so that rule does not
-- need to be duplicated here.

create or replace function public.dv_generate_series_occurrences(
  p_series_id integer,
  p_horizon_years integer default 3
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_series           record;
  v_account          record;
  v_local_today      date;
  v_scheduled_id     integer;
  v_year             integer;
  v_month            integer;
  v_day              integer;
  v_occurrence_date  date;
  v_inserted_count   integer := 0;
  v_source_recurring_id integer;
begin
  select * into v_series from public.dv_event_series where series_id = p_series_id;
  if not found or v_series.deleted_at is not null or v_series.is_active = false then
    return 0;
  end if;

  if v_series.rrule is null or upper(v_series.rrule) not like 'FREQ=YEARLY%' then
    return 0; -- weekly/daily/monthly rrules not implemented yet
  end if;

  select a.* into v_account from public.dv_account a where a.account_id = v_series.account_id;
  if not found then
    return 0;
  end if;

  v_local_today := (now() at time zone v_account.timezone)::date;
  v_month := extract(month from v_series.start_date);
  v_day := extract(day from v_series.start_date);

  select event_status_id into v_scheduled_id
    from public.dv_event_status where event_status = 'scheduled';
  -- Generated occurrences are always tagged 'recurring_series' regardless of what the series
  -- record itself used as its event_source_id (usually 'web_dashboard', per the spec's "usually
  -- dashboard" note on dv_event_series.event_source_id) -- this is what lets the dashboard
  -- distinguish an auto-generated occurrence row from a hand-typed one.
  select event_source_id into v_source_recurring_id
    from public.dv_event_source where event_source = 'recurring_series';

  for v_year in extract(year from v_series.start_date)::integer
    .. (extract(year from v_local_today)::integer + p_horizon_years)
  loop
    -- Feb 29 birthdays fall back to Feb 28 in non-leap years.
    begin
      v_occurrence_date := make_date(v_year, v_month, v_day);
    exception when others then
      v_occurrence_date := make_date(v_year, 2, 28);
    end;

    if v_occurrence_date < v_series.start_date then
      continue;
    end if;
    if v_series.end_date is not null and v_occurrence_date > v_series.end_date then
      continue;
    end if;

    insert into public.dv_event (
      account_id, title, description, event_date, start_time, end_time,
      event_type_id, event_status_id, event_visibility_id, event_source_id,
      event_accuracy_id, display_priority, show_on_display, series_id,
      created_by_user_id, updated_by_user_id
    )
    select
      v_series.account_id, v_series.title, v_series.description, v_occurrence_date,
      v_series.start_time, v_series.end_time, v_series.event_type_id, v_scheduled_id,
      v_series.event_visibility_id, v_source_recurring_id, v_series.event_accuracy_id,
      v_series.display_priority, v_series.show_on_display, v_series.series_id,
      v_series.updated_by_user_id, v_series.updated_by_user_id
    where not exists (
      select 1 from public.dv_event e
      where e.series_id = v_series.series_id and e.event_date = v_occurrence_date
    );

    if found then
      v_inserted_count := v_inserted_count + 1;
    end if;
  end loop;

  return v_inserted_count;
end;
$$;

revoke all on function public.dv_generate_series_occurrences(integer, integer) from public;
revoke all on function public.dv_generate_series_occurrences(integer, integer) from anon;
grant execute on function public.dv_generate_series_occurrences(integer, integer) to authenticated;

-- ============================================================================
-- 4b. dv_sync_series_occurrences(): push a series-level edit out to existing occurrences
-- ============================================================================
-- Implements "editing the series updates future, non-overridden occurrences only": on a series
-- UPDATE, pushes the series' current field values onto every dv_event row for that series that
-- is not individually overridden, not cancelled, not soft-deleted, and dated today or later.
-- Past occurrences and series_overridden=true occurrences are left untouched.

create or replace function public.dv_sync_series_occurrences(p_series_id integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_series         record;
  v_account        record;
  v_local_today    date;
  v_cancelled_id   integer;
  v_updated_count  integer;
begin
  select * into v_series from public.dv_event_series where series_id = p_series_id;
  if not found or v_series.deleted_at is not null then
    return 0;
  end if;

  select a.* into v_account from public.dv_account a where a.account_id = v_series.account_id;
  if not found then
    return 0;
  end if;

  v_local_today := (now() at time zone v_account.timezone)::date;

  select event_status_id into v_cancelled_id
    from public.dv_event_status where event_status = 'cancelled';

  update public.dv_event e
  set title = v_series.title,
      description = v_series.description,
      start_time = v_series.start_time,
      end_time = v_series.end_time,
      event_type_id = v_series.event_type_id,
      event_visibility_id = v_series.event_visibility_id,
      event_accuracy_id = v_series.event_accuracy_id,
      display_priority = v_series.display_priority,
      show_on_display = v_series.show_on_display,
      updated_by_user_id = v_series.updated_by_user_id
  where e.series_id = v_series.series_id
    and e.series_overridden = false
    and e.deleted_at is null
    and e.event_date >= v_local_today
    and e.event_status_id is distinct from v_cancelled_id;

  get diagnostics v_updated_count = row_count;
  return v_updated_count;
end;
$$;

revoke all on function public.dv_sync_series_occurrences(integer) from public;
revoke all on function public.dv_sync_series_occurrences(integer) from anon;
grant execute on function public.dv_sync_series_occurrences(integer) to authenticated;

create or replace function public.dv_event_series_generate_on_write()
returns trigger
language plpgsql
as $$
declare
  -- new.series_id is bigint (dv_event_series' identity column); the functions below take
  -- integer, and bigint->integer is only an assignment cast, not an implicit one, so it must go
  -- through a typed local variable rather than being passed directly as a call argument.
  v_series_id integer;
begin
  v_series_id := new.series_id;
  if tg_op = 'UPDATE' then
    perform public.dv_sync_series_occurrences(v_series_id);
  end if;
  perform public.dv_generate_series_occurrences(v_series_id);
  return new;
end;
$$;

create trigger dv_event_series_generate_after_write
  after insert or update on public.dv_event_series
  for each row execute function public.dv_event_series_generate_on_write();

-- ============================================================================
-- 5. dv_refresh_all_event_series_occurrences(): monthly top-up for all series
-- ============================================================================
-- Yearly recurrence only materializes `p_horizon_years` years ahead at series create/edit
-- time, so a series nobody touches again would eventually run out of future occurrences.
-- Scheduled via pg_cron in a follow-up migration.

create or replace function public.dv_refresh_all_event_series_occurrences()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_series_id integer;
begin
  for v_series_id in
    select series_id from public.dv_event_series
    where deleted_at is null and is_active = true
  loop
    perform public.dv_generate_series_occurrences(v_series_id);
  end loop;
end;
$$;

revoke all on function public.dv_refresh_all_event_series_occurrences() from public;
revoke all on function public.dv_refresh_all_event_series_occurrences() from anon;
revoke all on function public.dv_refresh_all_event_series_occurrences() from authenticated;
